### ISSUE TITLE
Using with docker

### ISSUE THREAD

**Issue by matheusmota** [LodLive/LodView#44]
Hi there. Congrats on such great work!
Can you help me deploying it using Docker?
How can I configure the instance? Are there envvars?

Thanks

**Comment by ThomasThelen** [comment]
The following works fine on my end, are you running into any issues?

```
git clone https://github.com/LodLive/LodView.git
cd LodView
docker build -t lodview .
docker run -p 8080:8080 lodview
```

If you want to have a more configurable deployment I suggest making the modifications to the config.ttl file as [appropriate](https://github.com/LodLive/LodView/wiki/how-to%3A-install-and-configure-%28fast-method%29). These changes will then be packaged into the war file and deployed in the dockerized instance.

**Comment by KonradHoeffner** [comment]
As environment variables don't seem to have an effect right now, I use the following workaround in a Dockerfile from within a docker-compose setup, in this example with a custom Virtuoso SPARQL endpoint:

## ./docker-compose.yml (excerpt)

```yml
  virtuoso:          
    build: ./virtuoso
    volumes:
      - virtuoso-data:/data
      - ../mydata/data/toLoad:ro
    ports:
      - "8081:8890"

  lodview:
    build:
      context: ./lodview
      args:
        - SPARQL_ENDPOINT=http://virtuoso:8890/sparql
    ports:
      - "127.0.0.1:8889:8080"
    depends_on: 
      - virtuoso
    restart: unless-stopped
```


## ./lodview/Dockerfile
```yml
FROM maven:3-jdk-8 AS builder
WORKDIR /app
ARG SPARQL_ENDPOINT=https://www.yourdefaultendpoint.com/sparql
RUN wget --no-verbose https://github.com/yourorganizationwhereyouforkit/lodview/archive/refs/heads/master.zip \
 && unzip -q master.zip \
 && mv lodview-master/* . \
 && sed -i "s|https://www\.yourdefaultendpoint\.com/sparql|${SPARQL_ENDPOINT}|" src/main/webapp/WEB-INF/conf.ttl \
 && ls lodview-master \
 && rm -rf lodview-master \
 && rm master.zip    
RUN mvn -B -q compile war:war
      
FROM tomcat:9-jre8-slim
ENV CATALINA_OPTS="-XX:+UseSerialGC"
COPY --from=builder /app/target/lodview.war /usr/local/tomcat/webapps/ontology.war
COPY logging.properties /usr/local/tomcat/conf
EXPOSE 8080
```

It's not pretty but it works at least for now as a workaround.
